[platformio]
; --- generic options ---
description  = Firmware for ESP8266/ESP32 by olonsoft Dimitris Paterakis
default_envs = nodemcuv2-work
; --- directory options ---
build_dir    = ${sysenv.TEMP}\pio\build

[common]
build_flags =
    ; -std=gnu++17
    -DAPP_ENV=\"development\"
    -D_GNU_SOURCE
    -D OLON_JSON_SUPPORT
    -D OLON_DEBUG_SYSTEM
    -D OLON_DEBUG_CONFIG
    -D CONFIG_ARDUHAL_LOG_COLORS
    -D OLOG_COLORS
    -D OLON_DEBUG
    -D ESPCONNECT_DEBUG
    ; -D DEBUG_ESP_CORE
    ; -D DEBUG_ESP_WIFI
    ; -D CORE_DEBUG_LEVEL=5 ; 0=None 1=Error 2=Warn 3=Info 4=Debug 5=Verbose
    -DMQTT_MAX_PACKET_SIZE=1024 ; for pubsubclient library
    ; --- optimization flags ---
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -fno-exceptions
build_unflags =
    ; -std=gnu++11
build_type = debug ; change to "release" for production firmware
monitor_filters = direct
lib_deps =
    symlink://../esp-framework
    ; WiFiManager
    ; bblanchon/ArduinoJson
    ; symlink://../../../../mylibs/OlonSystem
    ; symlink://../../../../mylibs/OlonLedBlinker
    ; symlink://../../../../mylibs/OlonConfig
    ; symlink://../../../../mylibs/OlonLogger2
    ; symlink://../../../../mylibs/OlonHADiscovery
    ; symlink://../../../../mylibs/OlonTaskManager2
    ; symlink://../../../../mylibs/OlonFOTA
    ; symlink://../../../../mylibs/OlonAnalogRead
    ; symlink://../../../../mylibs/OlonDS18Manager
    ; symlink://../../../../mylibs/OlonTime

    ; mathertel/OneButton
    ; hmueller01/PubSubClient3


[env]
; --- upload options ---
upload_speed    = 921600 ; valid values 300, 600, 1200, 2400, 4800, 9600, 19200, 38400, 57600, 74880, 115200, 230400, 256000, 460800, 921600, 1843200, 3686400
; --- monitor options ---
monitor_speed   = 115200


[env:nodemcuv2-work]
platform          = espressif8266@^4.2.1
board             = nodemcuv2
framework         = arduino
; --- build options ---
build_flags       = ${common.build_flags}
build_unflags     = ${common.build_unflags}
build_type        = ${common.build_type}
; --- library options ---
lib_deps          =
  ${common.lib_deps}
  adafruit/DHT sensor library@^1.4.7
  milesburton/DallasTemperature@^4.0.6
; --- filters ---
monitor_filters   =
    ${common.monitor_filters}
    esp8266_exception_decoder
; upload_port     = COM4
; monitor_port    = COM4

[env:nodemcuv2-home]
platform          = espressif8266@^4.2.1
board             = nodemcuv2
framework         = arduino
; --- build options ---
build_flags       = ${common.build_flags}
build_unflags     = ${common.build_unflags}
build_type        = ${common.build_type}
; --- library options ---
lib_deps          =
  ${common.lib_deps}
  adafruit/DHT sensor library@^1.4.7
  milesburton/DallasTemperature@^4.0.6
; --- filters ---
monitor_filters   =
    ${common.monitor_filters}
    esp8266_exception_decoder
upload_port     = COM4
monitor_port    = COM4

[env:lolin_s2_mini]
platform          = espressif32
board             = lolin_s2_mini
framework         = arduino
build_flags       = ${common.build_flags}
build_unflags     = ${common.build_unflags}
build_type        = ${common.build_type}
board_build.partitions = partitions_custom.csv
lib_deps          =
    ${common.lib_deps}
    adafruit/DHT sensor library@^1.4.7
    milesburton/DallasTemperature@^4.0.6
monitor_filters   =
    ${common.monitor_filters}
    esp32_exception_decoder

[env:esp32dev]
platform          = espressif32
board             = esp32dev
framework         = arduino
build_flags       = ${common.build_flags}
build_unflags     = ${common.build_unflags}
build_type        = ${common.build_type}
board_build.partitions = partitions_custom.csv
lib_deps          =
    ${common.lib_deps}
    adafruit/DHT sensor library@^1.4.7
    milesburton/DallasTemperature@^4.0.6
monitor_filters   =
    ${common.monitor_filters}
    esp32_exception_decoder